export const fall1110 = {
  strm: 2769,
  crseId: 358526,
  crseOfferNbr: 1,
  subject: 'CS',
  catalogNbr: '1110',
  titleShort: 'Intro Computing Using Python',
  titleLong: 'Introduction to Computing Using Python',
  enrollGroups: [
    {
      classSections: [Array],
      unitsMinimum: 4,
      unitsMaximum: 4,
      componentsOptional: [],
      componentsRequired: [Array],
      gradingBasis: 'GRI',
      gradingBasisShort: 'GradeNoAud',
      gradingBasisLong: 'Letter grades only (no audit)',
      simpleCombinations: [],
      sessionCode: '1',
      sessionBeginDt: '09/02/2020',
      sessionEndDt: '12/21/2020',
      sessionLong: 'Regular Academic Session',
    },
  ],
  description: 'Programming and problem solving using Python. Emphasizes principles of software development, style, and testing. Topics include procedures and functions, iteration, recusion, arrays and vectors, strings, an operational model of procedure and function calls, algorithms, exceptions, object-oriented programming, and GUIs (graphical user interfaces). Weekly labs provide guided practice on the computer, with staff present to help. Assignments use graphics and GUIs to help develop fluency and understanding.',
  catalogBreadth: '',
  catalogDistr: '(MQR-AS, SMR-AS)',
  catalogLang: '',
  catalogForbiddenOverlaps: 'Forbidden Overlap: due to a partial overlap in content, students will receive 6 credits instead of 8 if they take CS 1110 and one of the following: CS 1112, CS 1115, INFO 1100, VISST 1100.',
  catalogAttribute: '',
  catalogWhenOffered: 'Fall, Spring, Summer.',
  catalogComments: 'Assumes basic high school mathematics. No calculus or programming experience required. Students may not enroll in CS 1110 if they have taken or are also enrolled in CS 2110/ENGRD 2110, CS 2112, or have taken or are currently enrolled in a course offered or cross-listed with a CS number 3000 or above. (Students looking to learn Python rather than learn how to program should take CS 1133 instead.) Students who have affiliated with the computer-science major may not enroll.',
  catalogPrereqCoreq: '',
  catalogFee: '',
  catalogSatisfiesReq: '',
  catalogPermission: '',
  catalogCourseSubfield: '',
  catalogOutcomes: [
    'Be fluent in the use of procedural statements -assignments, conditional statements, loops, method calls- and  arrays. Be able to design, code, and test small Python programs that meet requirements expressed in English. This includes a basic understanding of top-down design.',
    'Understand the concepts of object-oriented programming as used in Python: classes, subclasses, inheritance, and overriding.',
    'Have knowledge of basic searching and sorting algorithms. Have knowledge of the basics of vector computation.',
  ],
  acadCareer: 'UG',
  acadGroup: 'EN',
}

export const spring1110 = {
  strm: 2783,
  crseId: 358526,
  crseOfferNbr: 1,
  subject: 'CS',
  catalogNbr: '1110',
  titleShort: 'Intro Computing Using Python',
  titleLong: 'Introduction to Computing Using Python',
  enrollGroups: [
    {
      classSections: [Array],
      unitsMinimum: 4,
      unitsMaximum: 4,
      componentsOptional: [],
      componentsRequired: [Array],
      gradingBasis: 'OPI',
      gradingBasisShort: 'Opt NoAud',
      gradingBasisLong: 'Letter or S/U grades (no audit)',
      simpleCombinations: [],
      sessionCode: '1',
      sessionBeginDt: '02/08/2021',
      sessionEndDt: '05/25/2021',
      sessionLong: 'Regular Academic Session',
    },
  ],
  description: 'Programming and problem solving using Python. Emphasizes principles of software development, style, and testing. Topics include procedures and functions, iteration, recusion, arrays and vectors, strings, an operational model of procedure and function calls, algorithms, exceptions, object-oriented programming, and GUIs (graphical user interfaces). Weekly labs provide guided practice on the computer, with staff present to help. Assignments use graphics and GUIs to help develop fluency and understanding.',
  catalogBreadth: '',
  catalogDistr: '(MQR-AS, SMR-AS)',
  catalogLang: '',
  catalogForbiddenOverlaps: 'Forbidden Overlap: due to a partial overlap in content, students will receive 6 credits instead of 8 if they take CS 1110 and one of the following: CS 1112, CS 1115, INFO 1100, VISST 1100.',
  catalogAttribute: '',
  catalogWhenOffered: 'Fall, Spring, Summer.',
  catalogComments: 'Assumes basic high school mathematics. No calculus or programming experience required. Students may not enroll in CS 1110 if they have taken or are also enrolled in CS 2110/ENGRD 2110, CS 2112, or have taken or are currently enrolled in a course offered or cross-listed with a CS number 3000 or above. (Students looking to learn Python rather than learn how to program should take CS 1133 instead.) Students who have affiliated with the computer-science major may not enroll.',
  catalogPrereqCoreq: '',
  catalogFee: '',
  catalogSatisfiesReq: '',
  catalogPermission: '',
  catalogCourseSubfield: '',
  catalogOutcomes: [
    'Be fluent in the use of procedural statements -assignments, conditional statements, loops, method calls- and  arrays. Be able to design, code, and test small Python programs that meet requirements expressed in English. This includes a basic understanding of top-down design.',
    'Understand the concepts of object-oriented programming as used in Python: classes, subclasses, inheritance, and overriding.',
    'Have knowledge of basic searching and sorting algorithms. Have knowledge of the basics of vector computation.',
  ],
  acadCareer: 'UG',
  acadGroup: 'EN',
}
